### ISSUE TITLE
v1.0.1 Unity - 'EventManager' does not contain a definition for 'DispatcherDic'

### ISSUE THREAD

**Issue by BenjaminKobjolke** [ls9512/UEvent#1]
When I import the latest version from the unity package into unity I get the following error:
Assets\Plugins\UPlugins\UPlugins\Events\Unity\Script\Editor\EventMonitor.cs(140,54): error CS0117: 'EventManager' does not contain a definition for 'DispatcherDic'

**Comment by ls9512** [comment]
I'm sorry that the release version has not been tested in detail. You can temporarily solve this error by adding an `Assembly Definition` file in the root directory of the plug-in. I will update a version to fix this error later.

**Comment by ls9512** [comment]
> When I import the latest version from the unity package into unity I get the following error:
> Assets\Plugins\UPlugins\UPlugins\Events\Unity\Script\Editor\EventMonitor.cs(140,54): error CS0117: 'EventManager' does not contain a definition for 'DispatcherDic'

I'm sorry that we haven't tested the release version in detail. You can temporarily solve this problem by adding an `Assembly Definition` file in root folder. I will update the version as soon as possible to fix this problem.

**Comment by BenjaminKobjolke** [comment]
It's alright. I am still using an older version.
Will wait for your update.

By the way: This s a great libary :)
